//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_EntityAdoNet.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV
    {
        public int SVID { get; set; }
        public Nullable<int> SVCLID { get; set; }
        public string SVName { get; set; }
        public Nullable<double> SVDtb { get; set; }
        public Nullable<System.DateTime> SVNS { get; set; }
        public Nullable<bool> SVGender { get; set; }
        public Nullable<bool> SVPicture { get; set; }
        public Nullable<bool> SVHb { get; set; }
        public Nullable<bool> SVCccd { get; set; }
    
        public virtual LopSH LopSH { get; set; }
    }
}
